# Generated by Django 4.1.7 on 2023-03-30 14:06

from django.db import migrations, models
import phonenumber_field.modelfields
import siraiitm.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_site_name', models.CharField(help_text='IIT Madras B.S Degree', max_length=200, verbose_name='Site name')),
                ('support_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN', unique=True, verbose_name='Phone')),
                ('support_email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Support Email')),
                ('default_user_photo', models.ImageField(storage=siraiitm.utils.OverwriteStorage, upload_to='images/default/default_user.png')),
                ('default_site_logo', models.ImageField(storage=siraiitm.utils.OverwriteStorage, upload_to='images/default/default_logo.png')),
                ('default_site_favicon', models.ImageField(storage=siraiitm.utils.OverwriteStorage, upload_to='images/default/favicon.png')),
            ],
            options={
                'verbose_name_plural': 'Default Site Properties',
            },
        ),
    ]
