# Generated by Django 4.1.7 on 2023-03-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siraconfig', '0002_alter_defaults_default_site_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaults',
            name='default_portal_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Portal name'),
        ),
        migrations.AddField(
            model_name='defaults',
            name='default_portal_shortname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ShortForm'),
        ),
    ]
