# Generated by Django 4.1.7 on 2023-03-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='personal_email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Personal Email'),
        ),
    ]
