# Generated by Django 4.1.7 on 2023-03-30 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last updated'),
        ),
    ]
